### PR TITLE
Add Beyondcoin

### PR DESCRIPTION
**Pull request by Tech1k**
Adds ElectrumX support for Beyondcoin (BYND).

### CODE REVIEW

**Comment by SomberNight** [comment]
please add a unit test like other altcoins have

**Comment by Tech1k** [comment]
> please add a unit test like other altcoins have

Added. Would you like me to squash my commits?

**Comment by ecdsa** [comment]
we should get rid of all the shitcoins

**Comment by SomberNight** [comment]
The Travis tests failed; there is a whitespace issue, please fix.

> `$ pycodestyle --max-line-length=100 electrumx/server/*.py electrumx/lib/*.py *.py`
> electrumx/lib/coins.py:3860:1: E302 expected 2 blank lines, found 1
> The command "`pycodestyle --max-line-length=100 electrumx/server/*.py electrumx/lib/*.py *.py`" exited with 1.

**Comment by Tech1k** [comment]
> The Travis tests failed; there is a whitespace issue, please fix.
> 
> > `$ pycodestyle --max-line-length=100 electrumx/server/*.py electrumx/lib/*.py *.py`
> > electrumx/lib/coins.py:3860:1: E302 expected 2 blank lines, found 1
> > The command "`pycodestyle --max-line-length=100 electrumx/server/*.py electrumx/lib/*.py *.py`" exited with 1.

Whoops, didn't see that at first, should be fixed now with my latest commit!

**Pull request merged**
