### PR TITLE
Use stdlib for scrypt, bump CI to latest LTS distro for scrypt support.

### PR DESCRIPTION
**Pull request by JustinTArthur**
New Ubuntu LTS also has newer leveldb than PPA.

### CODE REVIEW

**Comment by SomberNight** [comment]
The diff looks good.
However the travis test segfaulted :/

**Comment by JustinTArthur** [comment]
Yep, that's unfortunate. I wonder if there's an incompatibility with recent kernels+glibc and the neoscrypt library.

**Comment by SomberNight** [comment]
We should test the `trusty` -> `bionic` change in isolation.

**Comment by JustinTArthur** [comment]
Mmhm, and unfortuntaley, yarl (and by proxy aiohttp) isn't Python 3.10 nightly compatible due to the change from `Py_SIZE` to `Py_SET_SIZE` even if we do fix neoscrypt.

**Comment by JustinTArthur** [comment]
I still don't know the source of the segfault, but yarl's issue with Python 3.10 compatibility is being tracked in aio-libs/yarl#457.

**Comment by SomberNight** [comment]
Well, IMHO we should just rm the guilty altcoins. They should figure out why their hash function is segfaulting. If someone cares, they should open a PR with a fix, and re-add them.

Re yarl issue, I think we should not test on `nightly`, it might add too much noise. We can also keep it and ignore it if you prefer (not really ideal either).

I was playing around a bit on this branch: https://github.com/spesmilo/electrumx/compare/202006_travis_bump_ubuntu
see last two commits in particular:
https://github.com/spesmilo/electrumx/commit/e897badc8eee4ca4aeb7c8a42c88f8909dbf2db4
https://github.com/spesmilo/electrumx/commit/067f6d7223299b6c9c396a859aad567ae7b13515
feel free to cherry-pick either if you agree

**Comment by tacaswell** [comment]
You have to re-cythonize yarl, the compatibility issues are a purely packaging related.

**Comment by JustinTArthur** [comment]
@tacaswell yep, we just don't want to make "re-cythonize yarl" part of our installation steps.

**Comment by JustinTArthur** [comment]
@zawasp and @eabz we'll probably remove neoscrypt coins for now. If sparkspay/python-neoscrypt#1 is resolved, feel free to submit pull requests for their reinstatement.

**Comment by eabz** [comment]
@JustinTArthur Thanks for contacting, no problem from me. I no longer use neoscrypt.

**Comment by JustinTArthur** [comment]
@SomberNight, the suggested changes are fine. I've updated the commits accordingly.

**Pull request merged**
