### PR TITLE
Dash v20 hardfork support

### PR DESCRIPTION
**Pull request by sapph1re**
Coinbase transactions with new fields are now supported and ElectrumX now synchronizes well.

Also removed legacy SubTx transactions.

### CODE REVIEW

**Comment by pshenmic** [comment]
The changes was tested against Dash Testnet v20 (dashpay/dashd:20.0.0-beta.4) and production server deployed at the

`dash-electrum-testnet.pshenmic.dev:50002`

Changes can be tested by anyone via latest dash electrum client (https://github.com/Bertrand256/electrum-dash)

**Review by pshenmic — APPROVED** [review]

**Comment by UdjinM6** [comment]
v20 just activated on mainnet at block 1987776 and I can confirm that this code seems to be working correctly

**Comment by UdjinM6** [comment]
@sapph1re could you pls try rebasing it and see if it helps?

**Comment by cipig** [comment]
i can confirm that the code works
updated our DASH electrums (https://1209k.com/bitcoin-eye/ele.php?chain=dash, the cipig.net ones) with this and they are back online after they initially crashed on HF activation

**Comment by UdjinM6** [comment]
Confirmed that rebasing fixes CI https://github.com/spesmilo/electrumx/pull/242

**Comment by SomberNight** [comment]
thanks

**Pull request merged**
